//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.WebServiceGTE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://en.wikipedia.org/wiki/Tempuri/", ConfigurationName="WebServiceGTE.wbsedxSoap")]
    public interface wbsedxSoap {
        
        // CODEGEN: Generating message contract since element name pXMLRequest from namespace http://en.wikipedia.org/wiki/Tempuri/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://en.wikipedia.org/wiki/Tempuri/funcsync", ReplyAction="*")]
        BL.WebServiceGTE.funcsyncResponse funcsync(BL.WebServiceGTE.funcsyncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://en.wikipedia.org/wiki/Tempuri/funcsync", ReplyAction="*")]
        System.Threading.Tasks.Task<BL.WebServiceGTE.funcsyncResponse> funcsyncAsync(BL.WebServiceGTE.funcsyncRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class funcsyncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="funcsync", Namespace="http://en.wikipedia.org/wiki/Tempuri/", Order=0)]
        public BL.WebServiceGTE.funcsyncRequestBody Body;
        
        public funcsyncRequest() {
        }
        
        public funcsyncRequest(BL.WebServiceGTE.funcsyncRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://en.wikipedia.org/wiki/Tempuri/")]
    public partial class funcsyncRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pXMLRequest;
        
        public funcsyncRequestBody() {
        }
        
        public funcsyncRequestBody(string pXMLRequest) {
            this.pXMLRequest = pXMLRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class funcsyncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="funcsyncResponse", Namespace="http://en.wikipedia.org/wiki/Tempuri/", Order=0)]
        public BL.WebServiceGTE.funcsyncResponseBody Body;
        
        public funcsyncResponse() {
        }
        
        public funcsyncResponse(BL.WebServiceGTE.funcsyncResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://en.wikipedia.org/wiki/Tempuri/")]
    public partial class funcsyncResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string funcsyncResult;
        
        public funcsyncResponseBody() {
        }
        
        public funcsyncResponseBody(string funcsyncResult) {
            this.funcsyncResult = funcsyncResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wbsedxSoapChannel : BL.WebServiceGTE.wbsedxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wbsedxSoapClient : System.ServiceModel.ClientBase<BL.WebServiceGTE.wbsedxSoap>, BL.WebServiceGTE.wbsedxSoap {
        
        public wbsedxSoapClient() {
        }
        
        public wbsedxSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wbsedxSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wbsedxSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wbsedxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BL.WebServiceGTE.funcsyncResponse BL.WebServiceGTE.wbsedxSoap.funcsync(BL.WebServiceGTE.funcsyncRequest request) {
            return base.Channel.funcsync(request);
        }
        
        public string funcsync(string pXMLRequest) {
            BL.WebServiceGTE.funcsyncRequest inValue = new BL.WebServiceGTE.funcsyncRequest();
            inValue.Body = new BL.WebServiceGTE.funcsyncRequestBody();
            inValue.Body.pXMLRequest = pXMLRequest;
            BL.WebServiceGTE.funcsyncResponse retVal = ((BL.WebServiceGTE.wbsedxSoap)(this)).funcsync(inValue);
            return retVal.Body.funcsyncResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BL.WebServiceGTE.funcsyncResponse> BL.WebServiceGTE.wbsedxSoap.funcsyncAsync(BL.WebServiceGTE.funcsyncRequest request) {
            return base.Channel.funcsyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<BL.WebServiceGTE.funcsyncResponse> funcsyncAsync(string pXMLRequest) {
            BL.WebServiceGTE.funcsyncRequest inValue = new BL.WebServiceGTE.funcsyncRequest();
            inValue.Body = new BL.WebServiceGTE.funcsyncRequestBody();
            inValue.Body.pXMLRequest = pXMLRequest;
            return ((BL.WebServiceGTE.wbsedxSoap)(this)).funcsyncAsync(inValue);
        }
    }
}
